### ISSUE TITLE
Remove CKAN logo

### ISSUE THREAD

**Issue by davidread** [timwis/jkan#121]
Whilst I'm all for innovation and disruption, and JKAN has lots going for it, but I think you should not appropriate a fellow open source project's logo - i.e. CKAN. Please will you remove it?

Compare JKAN logo:

<img width="545" alt="screen shot 2016-07-04 at 16 21 57" src="https://cloud.githubusercontent.com/assets/307612/16565163/7b1a164a-4203-11e6-8d0a-052e995f8c5a.png">

with CKAN logo:

![250_logo-ckan](https://cloud.githubusercontent.com/assets/307612/16565426/0278ad4e-4205-11e6-8b22-01ce51f24383.jpg)

**Comment by timwis** [comment]
Hi @davidread, I'm happy to remove it; never expected it to be off-putting to anyone. It's meant to look like a combination of the Jekyll logo and the CKAN logo, since it was inspired by CKAN. I wonder how different that is from forking CKAN, though I imagine there may be licensing issues with logos that I'm not aware of.

**Comment by davidread** [comment]
Thanks Tim.

I think it is healthy for each project to have its own identity with some clear gaps in between. Otherwise you might get confusion between them, or the sense that one is vouching for the other in some way.

**Comment by patcon** [comment]
I appreciate the train of thought, but my 2c:

- Submit a PR with a new logo to replace this one
- Wait until someone involved in the CKAN project takes issue and brings it up -- no need to anticipate an issue that isn't one yet ¯\_(ツ)_/¯
