### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by newideaslab** [timwis/jkan#162]
Hi there,
I am new to using jkan. I have followed the manual installation instructions and the demo looks good. When I log in with GitHub the right top bar is not displaying the "profile" or "log out" links. And in the admin page display an error when I try to save. Do I need to set up anything else?

Thanks for your help.

**Comment by timwis** [comment]
Hi @newideaslab, welcome 👋🏻 
When I login to your JKAN instance (anyone can login via github, but they can't do anything unless they have collaborator access on your repository), I see an error in the developer tools console. Looking at the network tab in the developer tools, it looks like the request made to your gatekeeper instance (the thing you setup on heroku) is returning a `503` error. That suggests the gatekeeper app isn't quite configured correctly on Heroku.

You can dig into that by going to the "logs" section of Heroku and seeing what the error messages are. My guess is it's something about the authentication with GitHub failing, and that's probably because (a) the GitHub token environment variable isn't quite right, or (b) when you created the GitHub token, you didn't use the correct callback URL.

Want to give that a look and see if it's resolved? Happy to help further if not. And, in the meantime, you can feel free to edit the files in your repository directly using the GitHub interface. It's not as sleek an experience, but just FYI it's available.

**Comment by newideaslab** [comment]
Great, I'll check the Heroku settings. Thank you very much! :)

**Comment by newideaslab** [comment]
Hi there! thank you for the great job creating jkan.
I'm still unable to admin. It seems to be a CORS problem in the authentification process. The system is adding a / at the end of the url.

![image](https://user-images.githubusercontent.com/81298097/113492058-9da3ac80-94ab-11eb-9254-80b7b2c79079.png)
 
![image](https://user-images.githubusercontent.com/81298097/113492133-f4a98180-94ab-11eb-84a5-f31e9da659dd.png)
