### ISSUE TITLE
Use data.json as dataset model/yml

### ISSUE THREAD

**Issue by JJediny** [timwis/jkan#34]
This would allow Data.gov to register data from future forks:
* https://github.com/project-open-data/datajson-builder/blob/gh-pages/data.json
* https://raw.githubusercontent.com/project-open-data/datajson-builder/gh-pages/_posts/examples/0100-01-01-travel-warnings.md

**Comment by timwis** [comment]
:+1: Good idea, and thanks for the example, that's perfect! Isn't there a table around somewhere that links POD fields to CKAN fields?

I was planning on matching the CKAN schema under the hood (as much as there is a "schema" in a collection of YAML documents) since the field names are pretty human readable, but let me know if there's a case for using another schema, like POD, by default.

**Comment by timwis** [comment]
:+1: sold on using data.json as the schema for JKAN. Posting this here for reference:

https://project-open-data.cio.gov/v1.1/metadata-resources/

**Comment by aborruso** [comment]
hi @timwis first of all thank you for JKAN: it's a great idea and a great product. I have written a [blog post](https://medium.com/open-data-stories/jkan-un-catalogo-opendata-leggero-per-davvero-61ec1f1905dc#.n386cutvd) in Italian (my language) about it and a friend of mine, after reading it, created a [JKAN portal](http://iltempe.github.io/opendatagentediprato/). Moreover he is creating an italian how-to guide. But I'm off-topic.

About github and publishing using "official" open data schema I think it's useful to look ad [git-data-publisher](http://theodi.org/blog/removing-barriers-to-publishing-open-data)

Best regards

**Comment by timwis** [comment]
Wow @aborruso, that's a really cool project idea! Thanks for pointing it out!

**Comment by timwis** [comment]
Resolved by befd4e0
